name=servoICS
version=0.0.0
author=MinteIiaShip
sentence=This library is for working with ICS standard (Kondo Kagaku). It is an unofficial and personal library.
paragraph=This library is for working with ICS standard (Kondo Kagaku). It is an unofficial and personal library.
category=Device Control
url=
architectures=esp32
