name=KrsServoFull
version=2.0.1
author=MinteIiaShip
sentence=A cross-board library for KRS Command-type Servos.
paragraph=This library can control a great number of servos.<br />It makes careful use of timers: the library can control 12 servos using only 1 timer.<br />On the Arduino Due you can control up to 60 servos.
category=Device Control
url=
architectures=avr,esp32
